# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install --save-dev expo-cli
  displayName: 'Install expo'

- script: |
    echo "$GOOGLE_SERVICES" > google-services.json
    echo "$FIREBASE_CONFIG_DEV" > ./src/config/authmiaajuda-firebase-dev.json
    echo "$FIREBASE_CONFIG" > ./src/config/authmiaajuda-firebase.json
    echo "$ENV_VARIABLE" > .env
  displayName: 'Config files'
  env: 
    GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    FIREBASE_CONFIG_DEV: ${{ secrets.FIREBASE_CONFIG_DEV }}
    FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    ENV_VARIABLE: ${{ secrets.ENV_VARIABLE }}  
  workingDirectory: 'app'
  
- script: npm install
  displayName: 'Install dependencies'
  workingDirectory: 'app'

- script: npx expo publish --non-interactive
  displayName: 'Expo publish'
  env:
    EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  workingDirectory: 'app'